#!/bin/bash


# Pre-Pathing: allow 'imagemin' command
PATH="/usr/bin:$PATH"


# track execution of script
log_file=/vagrant/log/imagemin.log
set -x;
exec &> >(while read -r line; do
  log_date=$(date +%Y-%m-%d:%H:%M:%S)
  printf "%s %s\n" "[$log_date]" "$line" >> "$log_file"
done)

# watch '[root_dir]/src/img/' subdirectory
inotifywait /vagrant/src/img/ -m -r -e close_write -e move --format %f |
  # Minify Images
  while read -r file; do
    # filename (without directory path)
    filename="${file##*/}"
    # get last `.` occurence as starting extension
    file_extension="${file##*.}"

    # minify with 'imagemin'
    if [ "$file_extension" = 'gif' ] || [ "$file_extension" = 'svg' ]; then
      cp /vagrant/src/img/"$file" /vagrant/webroot/sites/all/themes/custom/sample_theme/asset/img/"$filename"
    else
      imagemin /vagrant/src/img/"$file" > /vagrant/webroot/sites/all/themes/custom/sample_theme/asset/img/"$filename" &
    fi
  done
