#!/bin/bash

# @web_img: is executed from 'bash_loader', which is why the directory
#           paths seem shorter in this file (i.e. missing extra '../').
#
# Note: minifid GIF files lose their animated quality. This script minifies
#       all images except GIF (copied to the 'asset/').


# Pre-Pathing: allow 'imagemin' command
PATH="/usr/local/bin:$PATH"


# track execution of script
set -x; exec > /vagrant/log/imagemin_execution.log 2>&1


# watch '/vagrant/sites/all/themes/custom/sample_theme/src/img/' subdirectory
inotifywait /vagrant/sites/all/themes/custom/sample_theme/src/img/ -m -e close_write -e move -e create |
  # Minify Images
  while read path action file; do
    # filename (without directory path)
    filename="${file##*/}"
    file_extension="${file##*.}"

    # minify with 'imagemin'
    if [ "$file_extension" = 'gif' ]; then
      cp /vagrant/sites/all/themes/custom/sample_theme/src/img/"$file" /vagrant/sites/all/themes/custom/sample_theme/asset/img/"$filename"
    else
      imagemin /vagrant/sites/all/themes/custom/sample_theme/src/img/"$file" > /vagrant/sites/all/themes/custom/sample_theme/asset/img/"$filename"
    fi
  done
