#!/bin/bash

# @web_scss: is executed from 'bash_loader', which is why the directory
#            paths seem shorter in this file (i.e. missing extra '../').


# Pre-Pathing: allow 'sass' command
PATH="/usr/lib:$PATH"


# track execution of script
set -x; exec > /vagrant/log/sass_execution.log 2>&1


# watch '/vagrant/sites/all/themes/custom/sample_theme/src/scss/' subdirectory
inotifywait /vagrant/sites/all/themes/custom/sample_theme/src/scss/ -m -e close_write -e move --format %f |
  # Compile CSS
  while read -r file; do
    # get last `.` occurence as starting extension
    extension=${file##*.}
    # filename (without 'last' extension)
    filename="${file%.*}"

    if [ "$extension" = 'scss' ]
    then

      # compile with 'sass'
      node-sass /vagrant/sites/all/themes/custom/sample_theme/src/scss/"$file" /vagrant/sites/all/themes/custom/sample_theme/asset/css/"$filename".min.css --output-style compressed

    fi
  done
