#!/bin/bash

# @web_js: is executed from 'bash_loader', which is why the directory
#          paths seem shorter in this file (i.e. missing extra '../').


# Pre-Pathing: allow 'uglifyjs' command
PATH="/usr/bin:$PATH"


# track execution of script
set -x; exec > /vagrant/log/uglifyjs_execution.log 2>&1


# watch '/vagrant/src/js/' subdirectory
inotifywait /vagrant/src/js/ -m -e close_write -e move --format %f |
  # Minify Javascript
  while read -r file; do

      # get last `.` occurence as starting extension
      extension=${file##*.}
      # filename (without 'last' extension)
      filename="${file%.*}"

      if [ "$extension" = 'js' ]
      then

        # minifiy with 'uglifyjs'
        uglifyjs -c --output /vagrant/webroot/sites/all/themes/custom/sample_theme/asset/js/"$filename".min.js /vagrant/src/js/"$file"

      fi
  done
