#!/usr/bin/env ruby
#^syntax detection

## Declare puppet module repository
forge "https://forge.puppetlabs.com"

## Install Module: vcsrepo
mod 'vcsrepo',
  :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo.git",
  :ref => "1.3.0"

## Install Module: stdlib (apt dependency)
mod 'stdlib',
  :git => "https://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => "4.6.0"

## Install Module: nodejs
mod 'nodejs',
  :git => "https://github.com/puppet-community/puppet-nodejs.git",
  :ref => "1.1.0"