#!/usr/bin/env ruby
#^syntax detection

## Declare puppet module repository
forge "https://forge.puppetlabs.com"

## Install Module: stdlib (apt dependency)
mod 'stdlib',
  :git => "https://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => "4.6.0"